/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ModuleRouteImport } from './routes/$module'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as ReportsRevenueByRouteRouteImport } from './routes/reports/revenue-by-route'
import { Route as ReportsFleetUtilizationRouteImport } from './routes/reports/fleet-utilization'
import { Route as ReportsDeliveryPerformanceRouteImport } from './routes/reports/delivery-performance'

const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleRoute = ModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRevenueByRouteRoute = ReportsRevenueByRouteRouteImport.update({
  id: '/reports/revenue-by-route',
  path: '/reports/revenue-by-route',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsFleetUtilizationRoute = ReportsFleetUtilizationRouteImport.update({
  id: '/reports/fleet-utilization',
  path: '/reports/fleet-utilization',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsDeliveryPerformanceRoute =
  ReportsDeliveryPerformanceRouteImport.update({
    id: '/reports/delivery-performance',
    path: '/reports/delivery-performance',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$module': typeof ModuleRoute
  '/analytics': typeof AnalyticsRoute
  '/shipments': typeof ShipmentsRoute
  '/reports/delivery-performance': typeof ReportsDeliveryPerformanceRoute
  '/reports/fleet-utilization': typeof ReportsFleetUtilizationRoute
  '/reports/revenue-by-route': typeof ReportsRevenueByRouteRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$module': typeof ModuleRoute
  '/analytics': typeof AnalyticsRoute
  '/shipments': typeof ShipmentsRoute
  '/reports/delivery-performance': typeof ReportsDeliveryPerformanceRoute
  '/reports/fleet-utilization': typeof ReportsFleetUtilizationRoute
  '/reports/revenue-by-route': typeof ReportsRevenueByRouteRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$module': typeof ModuleRoute
  '/analytics': typeof AnalyticsRoute
  '/shipments': typeof ShipmentsRoute
  '/reports/delivery-performance': typeof ReportsDeliveryPerformanceRoute
  '/reports/fleet-utilization': typeof ReportsFleetUtilizationRoute
  '/reports/revenue-by-route': typeof ReportsRevenueByRouteRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$module'
    | '/analytics'
    | '/shipments'
    | '/reports/delivery-performance'
    | '/reports/fleet-utilization'
    | '/reports/revenue-by-route'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$module'
    | '/analytics'
    | '/shipments'
    | '/reports/delivery-performance'
    | '/reports/fleet-utilization'
    | '/reports/revenue-by-route'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/$module'
    | '/analytics'
    | '/shipments'
    | '/reports/delivery-performance'
    | '/reports/fleet-utilization'
    | '/reports/revenue-by-route'
    | '/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModuleRoute: typeof ModuleRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ShipmentsRoute: typeof ShipmentsRoute
  ReportsDeliveryPerformanceRoute: typeof ReportsDeliveryPerformanceRoute
  ReportsFleetUtilizationRoute: typeof ReportsFleetUtilizationRoute
  ReportsRevenueByRouteRoute: typeof ReportsRevenueByRouteRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$module': {
      id: '/$module'
      path: '/$module'
      fullPath: '/$module'
      preLoaderRoute: typeof ModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/revenue-by-route': {
      id: '/reports/revenue-by-route'
      path: '/reports/revenue-by-route'
      fullPath: '/reports/revenue-by-route'
      preLoaderRoute: typeof ReportsRevenueByRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/fleet-utilization': {
      id: '/reports/fleet-utilization'
      path: '/reports/fleet-utilization'
      fullPath: '/reports/fleet-utilization'
      preLoaderRoute: typeof ReportsFleetUtilizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/delivery-performance': {
      id: '/reports/delivery-performance'
      path: '/reports/delivery-performance'
      fullPath: '/reports/delivery-performance'
      preLoaderRoute: typeof ReportsDeliveryPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModuleRoute: ModuleRoute,
  AnalyticsRoute: AnalyticsRoute,
  ShipmentsRoute: ShipmentsRoute,
  ReportsDeliveryPerformanceRoute: ReportsDeliveryPerformanceRoute,
  ReportsFleetUtilizationRoute: ReportsFleetUtilizationRoute,
  ReportsRevenueByRouteRoute: ReportsRevenueByRouteRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
